### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by alexandreborges** [teambi0s/Wall-of-Shame#1]
Dear author,

Good evening. Your project seems interesting, but during the "python3 wallofshame.py --start traffic", I check the following scenario:

![image](https://user-images.githubusercontent.com/13165245/75194874-b0d83a80-5737-11ea-80db-15f017e4adcd.png)

Do have any idea about this issue? I've created the user, granted permission and create the API Token. 

Thank you for your attention.

**Comment by theevilsyn** [comment]
Hey @alexandreborges,

Sorry for the delay in response. Thanks for letting us know this. Well, as far as the issue is concerned, it looks like there has been some issue with the API token or framework communicating with the pineapple. I suggest you to try contacting the pineapple(retrieving client details etc.) using the API Token using the modules from ``pinemodules`` folder. Feel free to reach out if the issue still persists.

Thank You.
